services:
  inventory-mysql:
    image: mysql:8.3
    container_name: inventory-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'inventory_db'
      MYSQL_USER: 'inventoryuser'
      MYSQL_PASSWORD: 'Password1'
      MYSQL_ROOT_PASSWORD: 'Password1'
    ports:
      - "3308:3306"
    volumes:
      - inventory_data:/var/lib/mysql

  product-mysql:
    image: mysql:8.3
    container_name: product-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'product_db'
      MYSQL_USER: 'productuser'
      MYSQL_PASSWORD: 'Password12'
      MYSQL_ROOT_PASSWORD: 'Password12'
    ports:
      - "3307:3306"
    volumes:
      - product_data:/var/lib/mysql

  order-mysql:
    image: mysql:8.3
    container_name: order-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'order_db'
      MYSQL_USER: 'orderuser'
      MYSQL_PASSWORD: 'Password123'
      MYSQL_ROOT_PASSWORD: 'Password123'
    ports:
      - "3306:3306"
    volumes:
      - order_data:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.15
    networks:
      - broker-kafka
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.2.15
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  broker-kafka:
    driver: bridge

volumes:
  inventory_data:
  product_data:
  order_data: