CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sku VARCHAR(255) UNIQUE NOT NULL,
    quantity BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);