server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/api/products/**, /api/categories/**, /api/brands/**
        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/api/inventory/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/orders/**