server:
  port: 8083

spring:
  application:
    name: inventory
  r2dbc:
    url: r2dbc:mysql://localhost:3308/inventory_db
    username: inventoryuser
    password: Password1
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3308/inventory_db
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
    queues:
      inventory: inventory-update-queue