server:
  port: 8081

spring:
  application:
    name: order
  r2dbc:
    url: r2dbc:mysql://localhost:3306/order_db
    username: orderuser
    password: Password123
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/order_db
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: '1'