server:
  port: 8082

spring:
  application:
    name: order
  r2dbc:
    url: r2dbc:mysql://localhost:3307/order_db
    username: orderuser
    password: Password124
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3307/order_db
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer
      retries: '1'