server:
  port: 8082

spring:
  application:
    name: product
  r2dbc:
    url: r2dbc:mysql://localhost:3307/product_db
    username: productuser
    password: Password12
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3307/product_db
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
    topic:
      exchange: product-topic-exchange
    keys:
      inventory: product.inventory.#
      order: product.order.#
    queues:
      inventory: inventory-update-queue
      order: product-data-request-queue

#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: product-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      auto-offset-reset: earliest
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: "*"