server:
  port: 8081

spring:
  application:
    name: product
  r2dbc:
    url: r2dbc:mysql://localhost:3306/product_db
    username: root
    password: password123
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/product_db